version: "3.9"

services:
   app:
      image: devops-app
      container_name: devops_app_container
      depends_on:
      - redis
      command: ["sleep","3600"]

   redis:
     image: redis:7
     container_name: redis_container
     ports:
       - "6379:6379"	     
